language: go

install:
        - go get github.com/gohugoio/hugo

before_script:
        - rm -rf public 2> /dev/null

script:
        - hugo

deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        verbose: true
        keep-history: true
        local-dir: public
        target_branch: master
        on:
                branch: source
